# Generated by Django 5.2.5 on 2025-08-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='delivered_file',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='notes',
        ),
        migrations.AddField(
            model_name='designrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='instructions',
            field=models.TextField(default='Required'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designrequest',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
