# Generated by Django 5.2.5 on 2025-08-24 15:00

import orders.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orderitem_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='user_inputs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='orderupload',
            name='file',
            field=models.FileField(storage=orders.storage.ProtectedStorage(), upload_to='order_uploads/%Y/%m/%d/'),
        ),
    ]
